#!/usr/bin/bash
/usr/bin/autossh -fN -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -R [port-to-open-on-remote]:localhost:22 -p [port-of-remote-daemon] -i /root/.ssh/id_rsa -l username remotehost.example.com
